"""initial schema

Revision ID: 0fc8b7fa56db
Revises: 
Create Date: 2026-07-25 10:42:59.688662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fc8b7fa56db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mb_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('artist', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mb_id')
    )
    op.create_table('user_connections',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'connection_id')
    )
    op.create_table('connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_1_id', sa.Integer(), nullable=False),
    sa.Column('song_2_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['song_1_id'], ['songs.id'], ),
    sa.ForeignKeyConstraint(['song_2_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connections')
    op.drop_table('user_connections')
    op.drop_table('songs')
    # ### end Alembic commands ###
