"""add created_at to user_song_connections

Revision ID: 144092ecc0aa
Revises: ed0f67155696
Create Date: 2026-07-26 17:17:07.493625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '144092ecc0aa'
down_revision: Union[str, Sequence[str], None] = 'ed0f67155696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_song_connections', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_song_connections', 'created_at')
    # ### end Alembic commands ###
