"""add point attribute to user_song_connection

Revision ID: 6b9b1800fb23
Revises: bf751dbbf195
Create Date: 2026-07-27 19:19:55.427372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b9b1800fb23'
down_revision: Union[str, Sequence[str], None] = 'bf751dbbf195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_song_connections', sa.Column('points', sa.Float(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_song_connections', 'points')
    # ### end Alembic commands ###
